### ISSUE TITLE
Unity Render Error

### ISSUE THREAD

**Issue by wwxFromTju** [jsuarez5341/neural-mmo#24]
2020-05-31 10:35:39+0800 [-] failing WebSocket opening handshake ('Internal server error: 'LocalModeObjectID' object has no attribute 'clientData'')
2020-05-31 10:35:39+0800 [-] dropping connection to peer tcp4:127.0.0.1:63554 with abort=False: Internal server error: 'LocalModeObjectID' object has no attribute 'clientData'
2020-05-31 10:35:39+0800 [-] "127.0.0.1" - - [31/May/2020:02:35:39 +0000] "GET /forge/embyr/LegacyWebClient/favicon.ico HTTP/1.1" 200 21484 "http://localhost:8080/forge/embyr/LegacyWebClient/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
2020-05-31 10:35:39+0800 [-] Uptime:  40.2 , Tick:  67
2020-05-31 10:35:39+0800 [-] Unhandled error in Deferred:
2020-05-31 10:35:39+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/xxxxxxxx/anaconda3/envs/ma_transfer/lib/python3.6/site-packages/twisted/internet/base.py", line 1272, in run
	    self.mainLoop()
	  File "/Users/xxxxxxxx/anaconda3/envs/ma_transfer/lib/python3.6/site-packages/twisted/internet/base.py", line 1281, in mainLoop
	    self.runUntilCurrent()
	  File "/Users/xxxxxxxx/anaconda3/envs/ma_transfer/lib/python3.6/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/Users/xxxxxxxx/anaconda3/envs/ma_transfer/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/Users/xxxxxxxx/anaconda3/envs/ma_transfer/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/xxxxxxxx/source/env/my_world/neural-mmo/forge/embyr/twistedserver.py", line 142, in announce
	    client.sendUpdate()
	  File "/Users/xxxxxxxx/source/env/my_world/neural-mmo/forge/embyr/twistedserver.py", line 79, in sendUpdate
	    data = self.serverPacket()
	  File "/Users/xxxxxxxx/source/env/my_world/neural-mmo/forge/embyr/twistedserver.py", line 74, in serverPacket
	    data = self.realm.clientData()
	builtins.AttributeError: 'LocalModeObjectID' object has no attribute 'clientData'

**Comment by wwxFromTju** [comment]
data = self.realm.clientData() --> data = self.realm.value.clientData()
